ArtshopProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
# from artshop.views import ProductViewSet

# router = routers.DefaultRouter()
# router.register('san-pham', ProductViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('artshop.urls')),
    path('', include('customer.urls')),
    path('', include('cart.urls')), 
    path('', include('wishlist.urls')), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artshop/urls.py
from django.urls import path
from artshop.views import *

app_name = 'artshop'

urlpatterns = [
     path('', trang_chu, name='trang_chu'),
     path('danh-muc/<int:pk>/', danh_muc, name='danh_muc'),
     path('chi-tiet-san-pham/<int:pk>', chi_tiet_san_pham, name='chi_tiet_san_pham'),
     path('tim-kiem/', tim_kiem, name='tim_kiem'),
     path('lien-he/', lien_he, name='lien_he'),
     path('about/', about, name='about'),
]    

cart/urls.py
from django.urls import path
from cart.views import *

app_name = 'cart'
urlpatterns = [
     path('gio-hang/', gio_hang, name='gio_hang'),
     path('mua-ngay/<int:product_id>/', mua_ngay, name='mua_ngay'),
     path('xoa-san-pham/<int:product_id>/', xoa_san_pham, name='xoa_san_pham'),
     path('thanh-toan/', thanh_toan, name='thanh_toan'),
     path('them-vao-gio-hang/<int:product_id>/', them_vao_gio_hang, name='them_vao_gio_hang'),
]

customer/urls.py
from django.urls import path
from customer.views import *

app_name = 'customer'
urlpatterns = [
     path('dang-nhap/', dang_nhap, name='dang_nhap'),
     path('dang-xuat/', dang_xuat, name='dang_xuat'),
     path('tai-khoan-cua-toi/', tai_khoan_cua_toi, name='tai_khoan_cua_toi'),
     path('xuat-bao-cao-don-hang/<int:pk>/', xuat_bao_cao_don_hang, name='xuat_bao_cao_don_hang'),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'
urlpatterns = [
     path('wishlist/', wishlist, name='wishlist'),
     path('xoa-san-pham-wishlist/<int:product_id>/', xoa_san_pham_wishlist, name='xoa_san_pham_wishlist'),
     path('them-vao-wishlist/<int:product_id>/', them_vao_wishlist, name='them_vao_wishlist'),
]

artshop/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)
    image = models.ImageField(upload_to='artshop/categories', default='artshop/categories/default.png')

    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=250)
    artist = models.CharField(max_length=250)
    image = models.ImageField(upload_to='artshop/images', default='artshop/images/default.png')
    price = models.FloatField(default=0.0)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    viewed = models.IntegerField(default=0)

    def __str__(self):
        return self.name
    
class Contact(models.Model):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)
    subject = models.CharField(max_length=200, null=True)
    message = models.TextField(null=True)
    created = models.DateTimeField(default=timezone.now)

cart/models.py
from django.db import models
from customer.models import Customer
from artshop.models import Product


# Create your models here.
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=1)
    discount = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.id)

wishlist/models.py
from django.db import models

# Create your models here.

artshop/forms.py
from django import forms
from artshop.models import Contact


class FormContact(forms.ModelForm):
    name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control fh5co_contact_text_box',
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control fh5co_contact_text_box',
    }))
    subject = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control fh5co_contact_text_box', 
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control fh5co_contacts_message', 
    }))

    class Meta:
        model = Contact
        # fields = ['name', 'email', 'subject', 'message']
        exclude = ['created']       # Khai bao tat ca tru 'created'

artshop/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from artshop.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  
from cart.cart import Cart
from wishlist.wishlist import Wishlist
from django.http import JsonResponse  
from rest_framework import viewsets, permissions
from artshop.serializers import ProductSerializer
from cart.views import them_vao_gio_hang
from wishlist.views import them_vao_wishlist
from urllib.parse import urlencode
from django.conf import settings
from artshop.forms import *

# Create your views here.

categories = Category.objects.all()



def trang_chu(request):
    cart = Cart(request)

    # Sản phẩm nổi bật
    most_viewed_products = Product.objects.order_by('-viewed')[:10]

    return render(request, 'artshop/index.html', {
        'categories': categories,
        'most_viewed_products': most_viewed_products,
        'cart': cart,

    })


def danh_muc(request, pk):
    # Giỏ hàng
    cart = Cart(request)
    
    
    if pk == 0:         # Đọc tất cả sản phẩm
        products = Product.objects.order_by('name')
        title_category = f'All Products ({len(products)})'
    else:              
        products = Product.objects.filter(category=pk).order_by('name')
        title_category = f'{Category.objects.get(pk=pk)} ({len(products)})'


    # Lọc giá
    range_gia = ''
    tu_khoa = ''
    if request.GET.get('gia'):
        range_gia = request.GET.get('gia')
        # print(range_gia)
        tu_gia, den_gia = range_gia.split('-')
        tu_khoa = request.GET.get('tu_khoa').strip()

        if pk == 0:
            if den_gia != '':
                products = Product.objects.filter(price__gte=tu_gia, price__lt=den_gia).order_by('name')
                if tu_khoa != '':
                    products = Product.objects.filter(price__gte=tu_gia, price__lt=den_gia, name__contains=tu_khoa).order_by('name')
            else:
                products = Product.objects.filter(price__gte=tu_gia).order_by('name')
                if tu_khoa != '':
                    products = Product.objects.filter(price__gte=tu_gia, name__contains=tu_khoa).order_by('name')


        else:
            products = Product.objects.filter(category=pk, price__gte=tu_gia).order_by('name')
            if den_gia  != '':
                products = Product.objects.filter(category=pk, price__gte=tu_gia, price__lt=den_gia).order_by('name')
                if tu_khoa != '':
                    products = Product.objects.filter(category=pk, price__gte=tu_gia, price__lt=den_gia, name__contains=tu_khoa).order_by('name')

        title_category = f'Found {len(products)} products'
    
    # Phân trang
    products_per_page = 12
    page = request.GET.get('trang', 1)
    paginator = Paginator(products, products_per_page)
    try: 
        products_pager = paginator.page(page)
    except PageNotAnInteger:
        products_pager = paginator.page(1)
    except EmptyPage:
        products_pager = paginator.page(paginator.num_pages)
    

    return render(request, 'artshop/shop.html', {
        'categories': categories, 
        'products': products,
        'products_pager': products_pager,               
        'cart': cart,
        'range_gia': range_gia,                     
        'keyword': tu_khoa,
        'title_category': title_category,
    })
    






def chi_tiet_san_pham(request, pk):

    # Chi tiết sản phẩm
    product = Product.objects.get(pk=pk)

    # Sản phẩm liên quan
    related_products = Product.objects.filter(category=product.category.pk).exclude(pk=pk).order_by('name')[:20]

    # Thêm vào giỏ hàng
    quantity = 1
    if request.POST.get('btnThemVaoGioHang'):
        quantity = int(request.POST.get('quantity'))
        print(quantity)
        them_vao_gio_hang(request, pk, quantity)


    # Load thông tin giỏ hàng
    cart = Cart(request)

    # Thống kê số lượt xem
    product.viewed += 1
    product.save()

    return render(request, 'artshop/shop-detail.html', {
        'cart': cart,
        'categories': categories,
        'product': product,
        'related_products': related_products,
        'quantity': quantity,
        

    })

def tim_kiem(request):
    # Giỏ hàng
    cart = Cart(request)

    # Tìm kiếm
    products = []
    keyword = ''
    if request.GET.get('tu_khoa'):
        keyword = request.GET.get('tu_khoa').strip()
        products = Product.objects.filter(name__contains=keyword).order_by('name')
        # print(products)
    title_category = f'Found {len(products)} products'

     # Lọc giá
    if request.GET.get('gia'):
        range_gia = request.GET.get('gia')
        keyword = request.GET.get('tu_khoa').strip()
        base_url = reverse('artshop:danh_muc', kwargs={'pk': 0})
        query_string = urlencode({'gia': range_gia, 'tu_khoa': keyword})
        url = f'{base_url}?{query_string}'
        return redirect(url)


    # Phân trang
    products_per_page = 12
    page = request.GET.get('trang', 1)
    paginator = Paginator(products, products_per_page)
    try:
        products_pager = paginator.page(page)
    except PageNotAnInteger:
        products_pager = paginator.page(1)
    except EmptyPage:
        products_pager = paginator.page(paginator.num_pages)


    return render(request, 'artshop/shop.html', {
        'cart': cart,
        'categories': categories,
        'products_pager': products_pager,
        'title_category': title_category,
        'keyword': keyword,
    })


def lien_he(request):
    cart = Cart(request)

    ket_qua_lien_he = ''
    form = FormContact()
    if request.POST.get('btnSend'):
        form = FormContact(request.POST, Contact)
        if form.is_valid():
            request.POST._mutable = True
            post = form.save(commit=False)
            post.name = form.cleaned_data['name']
            post.email = form.cleaned_data['email']
            post.subject = form.cleaned_data['subject']
            post.message = form.cleaned_data['message']
            post.save()

        ket_qua_lien_he = '''
                <div class="alert alert-success" role="alert">
                    Your message has been sent! Thank you!
                </div>
                '''
    return render(request, 'artshop/contact-us.html', {
        'cart': cart,
        'form': form,
        'ket_qua_lien_he': ket_qua_lien_he,
    })

def about(request):
    cart = Cart(request)
    return render(request, 'artshop/about.html', {
        'cart': cart
    })

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.cart import Cart
from artshop.models import Product
from customer.models import Customer
from cart.models import Order, OrderItem
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from datetime import datetime
from django.views.decorators.http import require_POST

# Create your views here.
def gio_hang(request):
    cart = Cart(request)
    # Cập nhật giỏ hàng
    if request.POST.get('btnCapNhatGioHang'):
        cart_new = {}
        for c in cart:
            quantity_new = int(request.POST.get('quantity2' + str(c['product'].pk)))
            if quantity_new > 0:
                product_cart = {
                    str(c['product'].pk): {
                    'quantity': quantity_new, 
                    'price': str(c['price']), 
                    'coupon': str(c['coupon'])
                    }
                }
                cart_new.update(product_cart)
                c['quantity'] = quantity_new    # Giữ lại giá trị mới trong ô
            else:
                cart.remove(c['product'])
        else:
            # Chờ khi nào vòng lặp chạy xong thì sẽ update lại session cart
            request.session['cart'] = cart_new
    
    # Sử dụng mã giảm giá
    ds_ma_giam_gia = [
        {'TTTH': 0.8},
        {'TND': 0.9}, 
    ]

    ma_giam_gia = ''
    if request.POST.get('btnMaGiamGia'):
        ma_giam_gia = request.POST.get('ma_giam_gia').strip()
        giam_gia = 1
        for dict_ma_giam_gia in ds_ma_giam_gia:
            if ma_giam_gia in dict_ma_giam_gia:
                giam_gia = dict_ma_giam_gia[ma_giam_gia]
            cart_new = {}
            for c in cart:
                product_cart = {
                    str(c['product'].pk): {
                        'quantity': c['quantity'], 
                        'price': str(c['price']), 
                        'coupon': str(giam_gia)
                    }
                }
                cart_new.update(product_cart)
                c['coupon'] = giam_gia    # Giữ lại giá trị coupon mới
            else:
                # Chờ khi nào vòng lặp chạy xong thì sẽ update lại session cart
                request.session['cart'] = cart_new
    
    return render(request, 'artshop/cart.html', {
        'cart': cart,
        'ma_giam_gia': ma_giam_gia,
        
    })




def thanh_toan(request):
    cart = Cart(request)

    if len(cart) == 0:
        return redirect('cart:gio_hang')
    
    # Đặt hàng => Lưu thông tin đơn hàng vào CSDL 
    if request.POST.get('btnDatHang'):
        khach_hang = Customer.objects.get(pk=request.session.get('s_khachhang')['id'])

        # Lưu vào table Order
        order = Order()
        order.customer = khach_hang
        order.total = cart.get_final_total_price()
        order.save()

        # Lưu vào table OrderItem
        for c in cart:
            OrderItem.objects.create(order=order, 
                                     product=c['product'],
                                     price=c['price'],
                                     quantity=c['quantity'],
                                     discount=c['price'] * c['quantity'] * (1 - c['coupon']),
                                     total_price=c['total_price']
                                     )

        # Gửi mail
        ngay_hien_tai = datetime.now()
        tieu_de = f"[{ngay_hien_tai.strftime('%Y%m%d%H%M%S')}] Đặt hàng thành công"
        nguoi_gui = settings.EMAIL_HOST_USER
        danh_sach_nguoi_nhan = [khach_hang.email]
        

        # Gửi thông tin plain text
        # noi_dung = 'Test mail'
        # send_mail(tieu_de, noi_dung, nguoi_gui, danh_sach_nguoi_nhan)


        # Gửi thông tin có định dạng
        noi_dung = '<p>Your Order:</p>'
        noi_dung += '<ul>'
        for c in cart:
            noi_dung += f"<li>{c['product']}</li>"
        noi_dung += '</ul>'
        msg = EmailMessage(tieu_de, noi_dung, nguoi_gui, danh_sach_nguoi_nhan)
        msg.content_subtype= 'html'
        msg.send()



        # Xóa tất cả sản phẩm ra khỏi giỏ hàng
        cart.clear()
        
        return render(request, 'cart/result.html', {
            'cart': cart,
        })


    return render(request, 'artshop/checkout.html', {
        'cart': cart, 
    })




@require_POST
def mua_ngay(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if request.POST.get('btnMuaNgay' + str(product_id)):
        quantity = int(request.POST.get('quantity' + str(product_id)))
        cart.add(product, quantity)
    return redirect('cart:gio_hang')


def them_vao_gio_hang(request, product_id, quantity):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product, quantity)



def xoa_san_pham(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:gio_hang')

wishlist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from wishlist.wishlist import Wishlist
from artshop.models import Product
from django.conf import settings
from datetime import datetime
from django.views.decorators.http import require_POST

# Create your views here.
def wishlist(request):
    wishlist = Wishlist(request)
    return render(request, 'artshop/wishlist.html', {
        'wishlist': wishlist,
        
    })





@require_POST


def them_vao_wishlist(request, product_id):
    wishlist = Wishlist(request)
    product = get_object_or_404(Product, id=product_id)
    if request.POST.get('btnThemVaoWishlist' + str(product_id)):
        quantity = int(request.POST.get('quantity' + str(product_id)))
        wishlist.add(product, quantity)
    return redirect('wishlist:wishlist')


def xoa_san_pham_wishlist(request, product_id):
    wishlist = Wishlist(request)
    product = get_object_or_404(Product, id=product_id)
    wishlist.remove(product)
    return redirect('wishlist:wishlist')

artshop/templates/artshop/_Master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Basic -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>TheArtshop | {% block title_tab %}{% endblock %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'artshop/images/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'artshop/images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'artshop/css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'artshop/css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'artshop/css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'artshop/css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <style>
        .active{
            color: red;
          }
    </style>

    <script>
        jQuery(function ($) {
            let path = window.location.href;
            $('.mn a').each(function () {
                if (this.href === path){
                    $(this).addClass('active')
                }
            });
        });
    </script>
</head>

<body>

    

    <!-- Start Main Top -->
    <header class="main-header">
        <!-- Start Navigation -->
        <nav class="navbar
                    navbar-expand-lg
                    navbar-light 
                    bg-light 
                    navbar-default 
                    bootsnav">
            <div class="container">
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                    <a class="navbar-brand" href="{% url 'artshop:trang_chu' %}"><img src="{% static 'artshop/images/logo123.png' %}" class="logo" alt=""></a>
                </div>
                <!-- End Header Navigation -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-menu">
                    

                    <ul class="navbar-nav mr-auto" data-in="fadeInDown" data-out="fadeOutUp">

                        <li class="nav-item mn">
                            <a class="nav-link" href="{% url 'artshop:trang_chu' %}"><b style="font-size: 18px">Home</b></a>
                        </li>

                        <li class="nav-item mn">
                            <a class="nav-link " href="{% url 'artshop:about' %}"><b style="font-size: 18px">About Us</b></a>
                        </li>

                        <li class="nav-item mn">
                            <a class="nav-link " href="{% url 'artshop:danh_muc' 0 %}"><b style="font-size: 18px">Product</b></a>
                        </li>

                        <li class="nav-item mn">
                            <a class="nav-link " href="{% url 'artshop:lien_he' %}"><b style="font-size: 18px">Contact Us</b></a>
                        </li>
                        
                    </ul>
                </div>
                <!-- /.navbar-collapse -->

                <!-- Start Atribute Navigation -->

                <div class="attr-nav">
                    <ul>
                        <li class="search">
                            <a href="#">
                                <i class="fa fa-search"></i>
                            </a></li>
                        <li class="cart"><a href="{% url 'cart:gio_hang' %}">
						<i class="fa fa-shopping-bag"></i>
                            <span class="badge">{{ cart|length }}</span>
					</a></li>
                    <li class="dropdown">
                        {% with session_khach_hang=request.session.s_khachhang %}
                            {% if session_khach_hang %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><b style="font-size:18px">{{ session_khach_hang.last_name }} {{ session_khach_hang.first_name }}</b></a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="{% url 'cart:gio_hang'%}">Cart</a></li>
                                    <li><a href="{% url 'cart:thanh_toan'%}">Checkout</a></li>
                                    <li><a href="{% url 'wishlist:wishlist'%}">Wishlist</a></li>
                                    <li><a href="{% url 'customer:tai_khoan_cua_toi'%}">My Account</a></li>
                                    <li><a href="{% url 'customer:dang_xuat'%}">Logout</a></li>
                                </ul>
                            {% else %}
                                <a href="{% url 'customer:dang_nhap'%}" class="nav-link" style="font-size:18px"><b>Login</b></a>
                            {% endif %}
                        {% endwith%}
                        
                    </li>
                    </ul>
                </div>
                <!-- End Atribute Navigation -->
            </div>
            
        </nav>
        <!-- End Navigation -->
    </header>
    <!-- End Main Top -->

    <!-- Start Top Search -->
    <div class="top-search">
        <form method="get" action="{% url 'artshop:tim_kiem' %}">
            <div class="container">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    <input type="text" name="tu_khoa" class="form-control"  value="{{ keyword }}" placeholder="Search..." autocomplete="off">
                    <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
                </div>
            </div>
        </form>
    </div>
    <!-- End Top Search -->








    {% block main_content %}{% endblock %}











    

    <!-- Start Footer  -->
    <footer>
        <div class="footer-main">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <div class="footer-widget">
                            <h4>About TheArtShop</h4>
                            <p>TheArtshop Project by TND</p>
                            <ul>
                                <li><a href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-pinterest-p" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fab fa-whatsapp" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <div class="footer-link">
                            <h4>Information</h4>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Customer Service</a></li>
                                <li><a href="#">Our Sitemap</a></li>
                                <li><a href="#">Terms &amp; Conditions</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Delivery Information</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12">
                        <div class="footer-link-contact">
                            <h4>Contact Us</h4>
                            <ul>
                                <li>
                                    <p><i class="fas fa-map-marker-alt"></i>Address: 227 Nguyễn Văn Cừ, <br>Phường 11, Quận 5, TPHCM<br>Việt Nam </p>
                                </li>
                                <li>
                                    <p><i class="fas fa-phone-square"></i>Phone: <a href="tel:+1-888705770">0979791008</a></p>
                                </li>
                                <li>
                                    <p><i class="fas fa-envelope"></i>Email: <a href="mailto:contactinfo@gmail.com">tranngocdung230506@gmail.com</a></p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer  -->

    <!-- Start copyright  -->
    <div class="footer-copyright">
        <p class="footer-company">All Rights Reserved. &copy; 2018 <a href="#">ThewayShop</a> Design By :
            <a href="https://html.design/">html design</a></p>
    </div>
    <!-- End copyright  -->

    <a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

    <!-- ALL JS FILES -->
    <script src="{% static 'artshop/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'artshop/js/popper.min.js' %}"></script>
    <script src="{% static 'artshop/js/bootstrap.min.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'artshop/js/jquery.superslides.min.js' %}"></script>
    <script src="{% static 'artshop/js/bootstrap-select.js' %}"></script>
    <script src="{% static 'artshop/js/inewsticker.js' %}"></script>
    <script src="{% static 'artshop/js/bootsnav.js.' %}"></script>
    <script src="{% static 'artshop/js/images-loded.min.js' %}"></script>
    <script src="{% static 'artshop/js/isotope.min.js' %}"></script>
    <script src="{% static 'artshop/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'artshop/js/baguetteBox.min.js' %}"></script>
    <script src="{% static 'artshop/js/jquery-ui.js' %}"></script>
    <script src="{% static 'artshop/js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'artshop/js/form-validator.min.js' %}"></script>
    <script src="{% static 'artshop/js/contact-form-script.js' %}"></script>
    <script src="{% static 'artshop/js/custom.js' %}"></script>
</body>

</html>